[personal]
name = "Jacopo Philip Moretti"
title = "Computer Science MSc student at EPFL"
subtitle = "Interested in formal methods for software/hardware systems"
phone = "+41 76 730 67 19"
email = "jacopo@quartztz.com"
website = "quartztz.com"
github = "github.com/quartztz"

[[education]]
title = "MSc in Computer Science"
institution = "EPFL"
date = "2024 - exp. 2027"
description = "Master's degree in Computer Science at EPFL, Lausanne. Specialization in _Foundations of Software_, interest in formal methods and theorem proving."
projects = ["Formalizing State-of-the-Art Theoretical Computer Science (Lean)"]
activities = [
  "Logistics Manager, CLIC (2024-2025)",
  "Head of Prevention, AGEPoly (2025)",
]

[[education]]
title = "BSc in Computer Science"
institution = "EPFL"
date = "2021 - 2024"
description = "Bachelor's degree in Computer Science at EPFL, Lausanne."
activities = [
  "Technical Manager, Fréquence Banane (2022-2024)",
  "Committee Member, PolyLAN",
]
relevant_coursework = ["Computer Language Processing", "Functional Programming"]

[[experience]]
title = "Research Intern"
company = "Jetbrains"
date = "Mar. 2026 - Aug. 2026"
description = "Intern in the Jetbrains Formalisation Team, working on the design and formalization of a type system for uniqueness types. Designing a framework to perform formally verified dataflow analysis in Lean given a language's formal semantics."

[[experience]]
title = "Chief Product Officer"
company = "Actualia"
date = "Sept. 2024 - Oct. 2025"
description = "Co-founder/Tech CPO at Actualia, a startup developing a mobile app for customized, AI-powered press reviews."
highlights = [
  "Led end-to-end design and development of all app screens and views in the Flutter mobile development framework, prioritizing user experience and feedback integration",
  "Led product development, managed design team and marketing",
]

[[experience]]
title = "Student Assistant"
company = "EPFL"
date = "2023 - 2026"
description = "Student assistant for various courses at EPFL. Assisted students on forums and at weekly help sessions."
positions = [
  { semester = "Fall 2025", course = "Formal Verification (CS550, Kunčak)", work = "Designed and graded labs and projects" },
  { semester = "Spring 2025", course = "Computer Language Processing (CS320, Kunčak)", work = "Assisted with exercise set design and lab and project grading" },
  { semester = "Fall 2023", course = "Software Construction (CS214, Odersky, Kunčak, Pit-Claudel)", work = "Implemented workflow for recording and editing 20+ video lectures" },
]

[skills]
languages = [
  "Italian (native)",
  "French (native)",
  "English (native)",
  "German (basic)",
]
programming = [
  "Scala",
  "Rust",
  "Python",
  "C",
  "Typescript",
  "Dart",
  "Lean",
  "Stainless",
  "Rocq",
]
tools = ["Git", "Docker", "Typst", "Proxmox", "LaTeX", "Markdown"]
design = ["Figma", "Adobe Suite", "Penpot"]
other = ["Audio Engineering", "Stagecraft", "Video Editing"]
